using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class AudioSyncModel
{
    [RealtimeProperty(1, true, true)]
    private bool _useAudio;

    [RealtimeProperty(2, true, true)]
    private float _dbValue;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class AudioSyncModel : RealtimeModel {
    public bool useAudio {
        get {
            return _cache.LookForValueInCache(_useAudio, entry => entry.useAudioSet, entry => entry.useAudio);
        }
        set {
            if (this.useAudio == value) return;
            _cache.UpdateLocalCache(entry => { entry.useAudioSet = true; entry.useAudio = value; return entry; });
            InvalidateReliableLength();
            FireUseAudioDidChange(value);
        }
    }
    
    public float dbValue {
        get {
            return _cache.LookForValueInCache(_dbValue, entry => entry.dbValueSet, entry => entry.dbValue);
        }
        set {
            if (this.dbValue == value) return;
            _cache.UpdateLocalCache(entry => { entry.dbValueSet = true; entry.dbValue = value; return entry; });
            InvalidateReliableLength();
            FireDbValueDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(AudioSyncModel model, T value);
    public event PropertyChangedHandler<bool> useAudioDidChange;
    public event PropertyChangedHandler<float> dbValueDidChange;
    
    private struct LocalCacheEntry {
        public bool useAudioSet;
        public bool useAudio;
        public bool dbValueSet;
        public float dbValue;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        UseAudio = 1,
        DbValue = 2,
    }
    
    public AudioSyncModel() : this(null) {
    }
    
    public AudioSyncModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireUseAudioDidChange(bool value) {
        try {
            useAudioDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireDbValueDidChange(float value) {
        try {
            dbValueDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.UseAudio, _useAudio ? 1u : 0u);
            length += WriteStream.WriteFloatLength((uint)PropertyID.DbValue);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.useAudioSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.UseAudio, entry.useAudio ? 1u : 0u);
            }
            if (entry.dbValueSet) {
                length += WriteStream.WriteFloatLength((uint)PropertyID.DbValue);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.UseAudio, _useAudio ? 1u : 0u);
            stream.WriteFloat((uint)PropertyID.DbValue, _dbValue);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.useAudioSet || entry.dbValueSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.useAudioSet) {
                stream.WriteVarint32((uint)PropertyID.UseAudio, entry.useAudio ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.dbValueSet) {
                stream.WriteFloat((uint)PropertyID.DbValue, entry.dbValue);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.UseAudio: {
                    bool previousValue = _useAudio;
                    _useAudio = (stream.ReadVarint32() != 0);
                    bool useAudioExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.useAudioSet);
                    if (!useAudioExistsInChangeCache && _useAudio != previousValue) {
                        FireUseAudioDidChange(_useAudio);
                    }
                    break;
                }
                case (uint)PropertyID.DbValue: {
                    float previousValue = _dbValue;
                    _dbValue = stream.ReadFloat();
                    bool dbValueExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.dbValueSet);
                    if (!dbValueExistsInChangeCache && _dbValue != previousValue) {
                        FireDbValueDidChange(_dbValue);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _useAudio = useAudio;
        _dbValue = dbValue;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
