using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class LightSyncModel
{
    [RealtimeProperty(1, true, true)]
    private bool _forceLightSync;

    [RealtimeProperty(2, true, true)]
    private int _leastConnectedClientID;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class LightSyncModel : RealtimeModel {
    public bool forceLightSync {
        get {
            return _cache.LookForValueInCache(_forceLightSync, entry => entry.forceLightSyncSet, entry => entry.forceLightSync);
        }
        set {
            if (this.forceLightSync == value) return;
            _cache.UpdateLocalCache(entry => { entry.forceLightSyncSet = true; entry.forceLightSync = value; return entry; });
            InvalidateReliableLength();
            FireForceLightSyncDidChange(value);
        }
    }
    
    public int leastConnectedClientID {
        get {
            return _cache.LookForValueInCache(_leastConnectedClientID, entry => entry.leastConnectedClientIDSet, entry => entry.leastConnectedClientID);
        }
        set {
            if (this.leastConnectedClientID == value) return;
            _cache.UpdateLocalCache(entry => { entry.leastConnectedClientIDSet = true; entry.leastConnectedClientID = value; return entry; });
            InvalidateReliableLength();
            FireLeastConnectedClientIDDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(LightSyncModel model, T value);
    public event PropertyChangedHandler<bool> forceLightSyncDidChange;
    public event PropertyChangedHandler<int> leastConnectedClientIDDidChange;
    
    private struct LocalCacheEntry {
        public bool forceLightSyncSet;
        public bool forceLightSync;
        public bool leastConnectedClientIDSet;
        public int leastConnectedClientID;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        ForceLightSync = 1,
        LeastConnectedClientID = 2,
    }
    
    public LightSyncModel() : this(null) {
    }
    
    public LightSyncModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireForceLightSyncDidChange(bool value) {
        try {
            forceLightSyncDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireLeastConnectedClientIDDidChange(int value) {
        try {
            leastConnectedClientIDDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.ForceLightSync, _forceLightSync ? 1u : 0u);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.LeastConnectedClientID, (uint)_leastConnectedClientID);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.forceLightSyncSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.ForceLightSync, entry.forceLightSync ? 1u : 0u);
            }
            if (entry.leastConnectedClientIDSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.LeastConnectedClientID, (uint)entry.leastConnectedClientID);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.ForceLightSync, _forceLightSync ? 1u : 0u);
            stream.WriteVarint32((uint)PropertyID.LeastConnectedClientID, (uint)_leastConnectedClientID);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.forceLightSyncSet || entry.leastConnectedClientIDSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.forceLightSyncSet) {
                stream.WriteVarint32((uint)PropertyID.ForceLightSync, entry.forceLightSync ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.leastConnectedClientIDSet) {
                stream.WriteVarint32((uint)PropertyID.LeastConnectedClientID, (uint)entry.leastConnectedClientID);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.ForceLightSync: {
                    bool previousValue = _forceLightSync;
                    _forceLightSync = (stream.ReadVarint32() != 0);
                    bool forceLightSyncExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.forceLightSyncSet);
                    if (!forceLightSyncExistsInChangeCache && _forceLightSync != previousValue) {
                        FireForceLightSyncDidChange(_forceLightSync);
                    }
                    break;
                }
                case (uint)PropertyID.LeastConnectedClientID: {
                    int previousValue = _leastConnectedClientID;
                    _leastConnectedClientID = (int)stream.ReadVarint32();
                    bool leastConnectedClientIDExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.leastConnectedClientIDSet);
                    if (!leastConnectedClientIDExistsInChangeCache && _leastConnectedClientID != previousValue) {
                        FireLeastConnectedClientIDDidChange(_leastConnectedClientID);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _forceLightSync = forceLightSync;
        _leastConnectedClientID = leastConnectedClientID;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
