using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NavigationSyncModel
{
    [RealtimeProperty(1, true, true)]
    private int _floor;

    [RealtimeProperty(2, true, true)]
    private Vector3 _position;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NavigationSyncModel : RealtimeModel {
    public int floor {
        get {
            return _cache.LookForValueInCache(_floor, entry => entry.floorSet, entry => entry.floor);
        }
        set {
            if (this.floor == value) return;
            _cache.UpdateLocalCache(entry => { entry.floorSet = true; entry.floor = value; return entry; });
            InvalidateReliableLength();
            FireFloorDidChange(value);
        }
    }
    
    public UnityEngine.Vector3 position {
        get {
            return _cache.LookForValueInCache(_position, entry => entry.positionSet, entry => entry.position);
        }
        set {
            if (this.position == value) return;
            _cache.UpdateLocalCache(entry => { entry.positionSet = true; entry.position = value; return entry; });
            InvalidateReliableLength();
            FirePositionDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NavigationSyncModel model, T value);
    public event PropertyChangedHandler<int> floorDidChange;
    public event PropertyChangedHandler<UnityEngine.Vector3> positionDidChange;
    
    private struct LocalCacheEntry {
        public bool floorSet;
        public int floor;
        public bool positionSet;
        public UnityEngine.Vector3 position;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Floor = 1,
        Position = 2,
    }
    
    public NavigationSyncModel() : this(null) {
    }
    
    public NavigationSyncModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireFloorDidChange(int value) {
        try {
            floorDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FirePositionDidChange(UnityEngine.Vector3 value) {
        try {
            positionDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Floor, (uint)_floor);
            length += WriteStream.WriteBytesLength((uint)PropertyID.Position, WriteStream.Vector3ToBytesLength());
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.floorSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Floor, (uint)entry.floor);
            }
            if (entry.positionSet) {
                length += WriteStream.WriteBytesLength((uint)PropertyID.Position, WriteStream.Vector3ToBytesLength());
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.Floor, (uint)_floor);
            stream.WriteBytes((uint)PropertyID.Position, WriteStream.Vector3ToBytes(_position));
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.floorSet || entry.positionSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.floorSet) {
                stream.WriteVarint32((uint)PropertyID.Floor, (uint)entry.floor);
                didWriteProperties = true;
            }
            if (entry.positionSet) {
                stream.WriteBytes((uint)PropertyID.Position, WriteStream.Vector3ToBytes(entry.position));
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Floor: {
                    int previousValue = _floor;
                    _floor = (int)stream.ReadVarint32();
                    bool floorExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.floorSet);
                    if (!floorExistsInChangeCache && _floor != previousValue) {
                        FireFloorDidChange(_floor);
                    }
                    break;
                }
                case (uint)PropertyID.Position: {
                    UnityEngine.Vector3 previousValue = _position;
                    _position = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    bool positionExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.positionSet);
                    if (!positionExistsInChangeCache && _position != previousValue) {
                        FirePositionDidChange(_position);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _floor = floor;
        _position = position;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
