using System.Collections;
using System.Collections.Generic;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class SyncRealityModel
{
    [RealtimeProperty(1, true, true)]
    private bool _isRealityOn;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class SyncRealityModel : RealtimeModel {
    public bool isRealityOn {
        get {
            return _cache.LookForValueInCache(_isRealityOn, entry => entry.isRealityOnSet, entry => entry.isRealityOn);
        }
        set {
            if (this.isRealityOn == value) return;
            _cache.UpdateLocalCache(entry => { entry.isRealityOnSet = true; entry.isRealityOn = value; return entry; });
            InvalidateReliableLength();
            FireIsRealityOnDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(SyncRealityModel model, T value);
    public event PropertyChangedHandler<bool> isRealityOnDidChange;
    
    private struct LocalCacheEntry {
        public bool isRealityOnSet;
        public bool isRealityOn;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        IsRealityOn = 1,
    }
    
    public SyncRealityModel() : this(null) {
    }
    
    public SyncRealityModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireIsRealityOnDidChange(bool value) {
        try {
            isRealityOnDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.IsRealityOn, _isRealityOn ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.isRealityOnSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.IsRealityOn, entry.isRealityOn ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.IsRealityOn, _isRealityOn ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.isRealityOnSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.isRealityOnSet) {
                stream.WriteVarint32((uint)PropertyID.IsRealityOn, entry.isRealityOn ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.IsRealityOn: {
                    bool previousValue = _isRealityOn;
                    _isRealityOn = (stream.ReadVarint32() != 0);
                    bool isRealityOnExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.isRealityOnSet);
                    if (!isRealityOnExistsInChangeCache && _isRealityOn != previousValue) {
                        FireIsRealityOnDidChange(_isRealityOn);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _isRealityOn = isRealityOn;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
