using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TeleportSyncModel
{
    [RealtimeProperty(1, true, true)]
    private bool _teleportIn;

    [RealtimeProperty(2, true, true)]
    private bool _teleportOut;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TeleportSyncModel : RealtimeModel {
    public bool teleportIn {
        get {
            return _cache.LookForValueInCache(_teleportIn, entry => entry.teleportInSet, entry => entry.teleportIn);
        }
        set {
            if (this.teleportIn == value) return;
            _cache.UpdateLocalCache(entry => { entry.teleportInSet = true; entry.teleportIn = value; return entry; });
            InvalidateReliableLength();
            FireTeleportInDidChange(value);
        }
    }
    
    public bool teleportOut {
        get {
            return _cache.LookForValueInCache(_teleportOut, entry => entry.teleportOutSet, entry => entry.teleportOut);
        }
        set {
            if (this.teleportOut == value) return;
            _cache.UpdateLocalCache(entry => { entry.teleportOutSet = true; entry.teleportOut = value; return entry; });
            InvalidateReliableLength();
            FireTeleportOutDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TeleportSyncModel model, T value);
    public event PropertyChangedHandler<bool> teleportInDidChange;
    public event PropertyChangedHandler<bool> teleportOutDidChange;
    
    private struct LocalCacheEntry {
        public bool teleportInSet;
        public bool teleportIn;
        public bool teleportOutSet;
        public bool teleportOut;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        TeleportIn = 1,
        TeleportOut = 2,
    }
    
    public TeleportSyncModel() : this(null) {
    }
    
    public TeleportSyncModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireTeleportInDidChange(bool value) {
        try {
            teleportInDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireTeleportOutDidChange(bool value) {
        try {
            teleportOutDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.TeleportIn, _teleportIn ? 1u : 0u);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.TeleportOut, _teleportOut ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.teleportInSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.TeleportIn, entry.teleportIn ? 1u : 0u);
            }
            if (entry.teleportOutSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.TeleportOut, entry.teleportOut ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.TeleportIn, _teleportIn ? 1u : 0u);
            stream.WriteVarint32((uint)PropertyID.TeleportOut, _teleportOut ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.teleportInSet || entry.teleportOutSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.teleportInSet) {
                stream.WriteVarint32((uint)PropertyID.TeleportIn, entry.teleportIn ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.teleportOutSet) {
                stream.WriteVarint32((uint)PropertyID.TeleportOut, entry.teleportOut ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.TeleportIn: {
                    bool previousValue = _teleportIn;
                    _teleportIn = (stream.ReadVarint32() != 0);
                    bool teleportInExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.teleportInSet);
                    if (!teleportInExistsInChangeCache && _teleportIn != previousValue) {
                        FireTeleportInDidChange(_teleportIn);
                    }
                    break;
                }
                case (uint)PropertyID.TeleportOut: {
                    bool previousValue = _teleportOut;
                    _teleportOut = (stream.ReadVarint32() != 0);
                    bool teleportOutExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.teleportOutSet);
                    if (!teleportOutExistsInChangeCache && _teleportOut != previousValue) {
                        FireTeleportOutDidChange(_teleportOut);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _teleportIn = teleportIn;
        _teleportOut = teleportOut;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
